version: '3.8'
services:
  front:
    image: nginx
    ports:
      - '8080:80'
    expose:
      - '8080'
    volumes:
      - ./services/front:/usr/share/nginx/html
    networks:
      - front
  back:
    image: node
    ports:
      - '8081:80'
    expose:
      - '8081'
    volumes:
      - ./services/back:/app
    working_dir: /app
    command: npm start
    environment:
      PORT: 80
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: bd
    depends_on:
      - bd
    networks:
      - back
  bd:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - back
volumes:
  mysql:
networks:
  front:
  back: